spring.application.name=leave-management
# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/leave_management_db
spring.datasource.username=postgres
spring.datasource.password=postgresql
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate — auto create/update tables
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf
spring.thymeleaf.cache=false

# App Port
server.port=8080
